### ISSUE TITLE
terraform bastion node 구성

### ISSUE THREAD

**Issue by drake-jin** [pickstudio/infrastructure#5]
### Tasks
- [x] basic asg terraformming
- [x] public EIP 생성후 attach할 수 있도록
- [x] security-group members 만 이용 할 수 있도록
- [x] docker, docker-compose 설치하기
- [x] haproxy도 구성한채로 bastion 노드 구성하기
